### PR TITLE
Scrolling the game map with the mouse now works off of the change

### PR DESCRIPTION
**Pull request by ghost**
in position of the mouse, rather than a constant value.

References #43

### CODE REVIEW

**Comment by dsegna** [comment]
Just tested this. The keyboard is scrolling in the OPPOSITE direction of the arrow key pressed.
Mouse scrolling is fine.

**Comment by ghost** [comment]
Sounds like this is an OS or browser issue. Your machine registers the keys opposite to what mine does. We'll have to account for different OS platform input schemes. I'll get on it.

**Comment by ghost** [comment]
Try the keyboard input again, but don't merge this request yet. I submitted the latest commit in Windows and it has crappy formatting. I'm going to format the code better on my Linux machine.

**Comment by dsegna** [comment]
just tested on my windows laptop and mac both using firefox. 
the keyCode variable is not changing between the two OS, so windows is now scrolling in the opposite direction.
reverting to original code works for both Mac and Windows, not sure about Linux

**Pull request merged**
